config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#top'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def top
  end

  def index
  	@post = Post.new
  	@posts = Post.all
  end

  def create
  	post = Post.new(post_params)
  	if post.save
  		flash[:notice] = "Book was successfully created"
  		redirect_to post_path(post)
  	else
  		render post_path(post)
  	end
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	post = Post.find(params[:id])
  	post.update(post_params)
  	redirect_to post_path(post)
  end

  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to posts_path(post)
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>edit</title>
</head>
<body>
<div class = "main-edit">
	<h1>Editing Book</h1>
	<%= form_for(@post) do |f| %>

  	<div class = "title">
		<h4>Title</h4>

		<%= f.text_field :title %>
  	</div>

 	<div class = "body">
		<h4>Body</h4>

		<%= f.text_area :body %>
  	</div>
		<p class = "update"><%= f.submit 'Update Book'%></p>
		<a><%= link_to 'Show', post_path(@post),class:"show_2" %></a> |
		<a><%= link_to 'Back', posts_path(@post),class:"back" %></a>
	<% end %>
</div>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>index</title>
</head>
<body>
	<main>
		<h1 class = books>Books</h1>
		<table>
			<thead>
				<tr>
					<th>Title</th><th>Body</th><th></th><th></th><th></th>
				</tr>
			</thead>
			<tbody>
					<% @posts.each do |post| %>
				 	<tr>
						<td><%= post.title %></td>
						<td><%= post.body %></td>
						<td class = "show"><%= link_to 'Show', post_path(post),class:"show_1" %></td>
						<td class = "edit"><%= link_to 'Edit', edit_post_path(post),class:"edit_1" %></td>
						<td class = "destroy"><%= link_to 'Destroy', post_path(post),class:"destroy_1" ,method: :delete %></td>
					 </tr>
					<% end %>
			</tbody>
		</table>

		<h2 class = "new-book">New book</h2>

		<%= form_for(@post) do |f| %>

		  <div class = "title">
			<h4>Title</h4>

			<%= f.text_field :title,class:"book_title" %>
		  </div>

		  <div class = "body">
			<h4>Body</h4>

			<%= f.text_area :body,class:"book_body" %>
		  </div>

			<p class = "submit"><%= f.submit 'Create Book'%></p>

		<% end %>
	</main>
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>show</title>
</head>
<body>
	<div class = "main-show">
		<% if flash[:notice] %>
		<div class = "flash">
			<%= flash[:notice] %>
		</div>
		<% end %>
		<p class = "show-title"><strong>Title:</strong><%= @post.title %></p>
		<p class = "show-body"><strong>Body:</strong><%= @post.body%></p>

		<a><%= link_to 'Edit', edit_post_path(@post),class:"edit_2" %></a> |
		<a><%= link_to 'Back', posts_path(@post),class:"back" %></a>
	</div>
</body>
</html>

app/views/posts/top.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>top</title>
</head>
<body>
	<div class = "top-page">
		<h1 class ="welcome">ようこそ Bookers へ!</h1>
		<div class = "explain">
			<p class = "explain1">Bookersでは、様々な書籍に関するあなたの意見や</p>
			<p class = "explain2">印象を交換し交換することができます</p>
			<p class = "start"><%= link_to "start", posts_path %></p>
		</div>
	</div>
</body>
</html>